### ISSUE TITLE
Can not excute the codes of nselightgcn.py

### ISSUE THREAD

**Issue by kkkkkobe** [downeykking/NSE#1]
“from torch.geometric.utils import spmm” is wrong
cannot import name 'spmm' from 'torch_geometric.utils'

**Comment by downeykking** [comment]
Hi. Thank you for your interest!
Could you please specify the version of the `torch-geometric` and `torch_sparse` you are using?
`spmm` is only supported in `torch-geometric>=2.2.0`.

**Comment by kkkkkobe** [comment]
OK, thanks for your reply. I would try to do. You make my day!
