### ISSUE TITLE
Some confusion about the code

### ISSUE THREAD

**Issue by kkkkkobe** [downeykking/NSE#2]
'sp_adj = SparseTensor(row=self._user, col=self._item, value=torch.ones( len(self._user)), sparse_sizes=(self.n_users, self.n_items))'
What do 'self._user' and 'self._item' stand for?

**Comment by downeykking** [comment]
Hi, it means the users and items of train data, such as:
```
users: [1, 2, 3, 4, 5]
items: [1, 3, 5, 7, 9]
```

**Comment by kkkkkobe** [comment]
So, `user_num == len(self._user) ?`

**Comment by downeykking** [comment]
> So, `user_num == len(self._user) ?`

Nope, `user_num` is the number of users in whole dataset(including train, valid, test) while `self._user` is the connected users in train_dataset's interactions. 

For example, the whole dataset has three users `[1, 2, 3]` and five items `[1, 2, 3, 4, 5]`. The interactions in the format of `(user, item)` are `[(1, 1), (1, 2), (2, 2), (2, 4), (2, 5), (3, 1), (3, 2), (3, 3), (3, 4)]`.

Assume we split the data into train dataset:
train: `[(1, 1), (2, 2), (2, 4), (3, 1), (3, 2), (3, 3)]`
Here, `len(self._user)` means `len([1, 2, 2, 3, 3, 3]) = 6` which is different from `user_num = 3`.
