### ISSUE TITLE
请教论文模型

### ISSUE THREAD

**Issue by njt123123** [downeykking/NSE#3]
不知道是不是我理解错了，论文中在进行GCN之前先做一次GCN操作，然后将进行了一次GCN得到的节点嵌入作为后面3层GCN的输入，那不就是和用随机初始化的节点嵌入做4层GCN一样吗，为什么效果会提升这么多？

**Comment by downeykking** [comment]
> 不知道是不是我理解错了，论文中在进行GCN之前先做一次GCN操作，然后将进行了一次GCN得到的节点嵌入作为后面3层GCN的输入，那不就是和用随机初始化的节点嵌入做4层GCN一样吗，为什么效果会提升这么多？

您好！感谢您对我们工作的关注。您理解的大部分是正确的，但是并不是使用的4层GCN，而是NSE（sum-pooling）+3层GCN。我们的核心观点在于GCN每次更新节点表征时是十分缓慢的，而协同过滤做的下游任务是预测u-i之间的交互，因此我们提前用sum-pooling将一阶邻域信息显式注入模型中，相当于为GCN做了较强的初始化，为模型的收敛提供了更好的路径。我们也做过全部用sum-pooling的实验，但是由于这种卷积模式并不具备GCN动态调节不同hop权重的能力，因此模型的性能也会有所下降。而sum-pooling+GCN，可以同时平衡初始化路径和GCN的高阶卷积能力。当然也可以有进一步的思考：能不能动态改变每一层卷积的方法，为下游任务找到最合适的路径？这个也是个可行的探索方向 :)

**Comment by njt123123** [comment]
sum-pooling操作就是聚合一阶邻域信息，但是没有做行和列的归一化，那整个模型就相当于4层GCN但是第1层没有做归一化？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "downeykking/NSE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [downeykking/NSE] 请教论文模型 (Issue #3)





  
不知道是不是我理解错了，论文中在进行GCN之前先做一次GCN操作，然后将进行了一次GCN得到的节点嵌入作为后面3层GCN的输入，那不就是和用随机初始化的节点嵌入做4层GCN一样吗，为什么效果会提升这么多？
  
您好！感谢您对我们工作的关注。您理解的大部分是正确的，但是并不是使用的4层GCN，而是NSE（sum-pooling）+3层GCN。我们的核心观点在于GCN每次更新节点表征时是十分缓慢的，而协同过滤做的下游任务是预测u-i之间的交互，因此我们提前用sum-pooling将一阶邻域信息显式注入模型中，相当于为GCN做了较强的初始化，为模型的收敛提供了更好的路径。我们也做过全部用sum-pooling的实验，但是由于这种卷积模式并不具备GCN动态调节不同hop权重的能力，因此模型的性能也会有所下降。而sum-pooling+GCN，可以同时平衡初始化路径和GCN的高阶卷积能力。当然也可以有进一步的思考：能不能动态改变每一层卷积的方法，为下游任务找到最合适的路径？这个也是个可行的探索方向 :)

**Comment by downeykking** [comment]
是的
